export { default as Header } from './header/Header'
export { default as Button } from './shared/Button'
export { default as Navbar } from './navbar/Navbar'
export {default as About} from './about/About'
export {default as Title} from './shared/Title'
